---
- name: check the switch version
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
    expected: OpenSwitch
  tasks:
    - include: tasks/cli/check_version.yaml
      tags: [ always, basic ]

- name: L2/L3 configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ops_intf_admin_state: up
    ops_debug: no
  roles:
    - { role: switch, tags: [ always, basic ] }

- name: L2/L3 configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ops_intf_admin_state: up
    ops_debug: no
  roles:
    - { role: switch, tags: [ always, basic ] }

- name: L2/L3 configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ops_intf_admin_state: up
    ops_debug: no
  roles:
    - { role: switch, tags: [ always, basic ] }

- name: check the switch hostname
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: no
  tasks:
    - include: tasks/cli/check_hostname.yaml
      tags: [ always, basic ]

- name: check the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: yes
  tasks:
    - include: tasks/cli/check_running_config.yaml
      tags: [ always, basic ]

- include: bgp.yaml
  tags: [ bgp ]

- name: setup management network
  hosts: docker
  gather_facts: no
  tasks:
  - name: run script
    script: >
      "{{docker_mgmt_network_script}}"
