---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3]
    bgp_routers:
      - as_number: 65007
        router_id: 172.16.14.2
        networks: [172.16.14.0/24, 172.16.24.0/24, 172.16.60.0/24]
        neighbors:
          - address: 172.16.14.1
            remote_as: 65001
          - address: 172.16.24.1
            remote_as: 65002
          - address: 172.16.60.1
            remote_as: 65006

ops_ports:
  - name: 1
    ipv4_address: 172.16.14.2/24
  - name: 2
    ipv4_address: 172.16.24.2/24
  - name: 3
    ipv4_address: 172.16.60.2/24
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
  - name: 9
  - name: 10
  - name: 11
  - name: 12
  - name: 13
  - name: 14
  - name: 15
  - name: 16
  - name: 17
  - name: 18
  - name: 19
  - name: 20
  - name: 21
  - name: 22
  - name: 23
  - name: 24
  - name: 25
  - name: 26
  - name: 27
  - name: 28
  - name: 29
  - name: 30
  - name: 31
  - name: 32
  - name: 33
  - name: 34
  - name: 35
  - name: 36
  - name: 37
  - name: 38
  - name: 39
  - name: 40
  - name: 41
  - name: 42
  - name: 43
  - name: 44
  - name: 45
  - name: 46
  - name: 47
  - name: 48
